### ISSUE TITLE
Cores dos gráficos

### ISSUE THREAD

**Issue by btwhelena** [mtayllan/devtime#1]
Oie! Tenho uma sugestão para o esquema de cores dos gráficos 🤓

As cores verde, amarelo e vermelho são familiares para a grande maioria dos usuários e devem ser utilizadas de forma a diminuir a carga cognitiva que o usuário deve ter ao utilizar sua aplicação, ou seja, fazer com que o usuário tenha que fazer **menos esforço** para usar, entender  e conseguir realizar tarefas de forma eficaz e eficiente em sua interface.

Por convenção, a cor amarelo costuma significar alerta. O vermelho representa perdas, perigo ou ações destrutivas. E o verde (e o azul também) é utilizado para exprimir sucesso, ganhos e até lucros. Na métrica de média de tempo, poderia ser aplicada uma cor que não comprometesse a ideia que o usuário tem da métrica, como rosa, roxo, etc. Ao ver a métrica amarela, o usuário pode pensar coisas como "o app acha que minha média está ruim", e ter sentimentos como ansiedade e insegurança. No lugar do amarelo, pode ser aplicada uma cor que não passe essa sensação, como rosa, roxo, etc. 

Além disso, notei que as cores das linguagens não estão padronizadas em todos os gráficos. Padronizar é importante pois facilita a identificação e a familiaridade com os dados :)

**Comment by mtayllan** [comment]
Muito obrigado pela sugestão! Faz total sentido. Vou fazer essa melhora!
